#!/usr/bin/env perl

# Copyright (c) 2017 Todd Freed <todd.freed@gmail.com>
# 
# This file is part of autominer.
# 
# autominer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# autominer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License

#
# autominer wrapper for https://github.com/nicehash/nheqminer
#

use strict;
use warnings;

use POSIX;

if($ARGV[0] eq "configured")
{
  system("$ENV{AUTOMINER_NHEQMINER_CUDA_PATH} -h 1>/dev/null 2>&1");
  print "yes\n" if $? == 0;
}
elsif($ARGV[0] eq "algos")
{
  print("equihash\n");
}
elsif($ARGV[0] eq "mine")
{
  my $intensity = 25;

  my @cmd = (
      "$ENV{AUTOMINER_NHEQMINER_CUDA_PATH}"
    , "-l", "$ENV{AUTOMINER_ALGO}.$ENV{AUTOMINER_NICEHASH_REGION}.nicehash.com:$ENV{AUTOMINER_PORT}"
    , "-u", "$ENV{AUTOMINER_USERNAME}"
  );

  if(defined $ENV{AUTOMINER_CARDS_SPACES})
  {
    push @cmd, "-cd", split(/ /, "$ENV{AUTOMINER_CARDS_SPACES}");
  }

  print STDERR (" >> nheqminer_cuda : @cmd\n");
  # nheqminer_cuda writes benchmark data to stderr
  POSIX::dup2(1, 2) or die;
  exec { $cmd[0] } @cmd;
}
elsif($ARGV[0] eq "perf")
{
  while(my $line = <STDIN>)
  {
    chomp $line;

    # [21:41:34][0x00007fef827db240] Speed [15 sec]: 504.006 I/s, 953.507 Sols/s
    if($line =~ /Speed.* ([0-9.]+) Sols\/s/i)
    {
      my $rate = $1;

      my $record = sprintf("%10u %s %s/s\n", time() - $^T, $rate, "s");
      POSIX::write(1, $record, length($record));
    }
  }
}
