#!/usr/bin/env perl

# Copyright (c) 2017 Todd Freed <todd.freed@gmail.com>
# 
# This file is part of autominer.
# 
# autominer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# autominer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License

#
# autominer wrapper for https://github.com/KlausT/ccminer-cryptonight
#

use strict;
use warnings;

use POSIX;

if($ARGV[0] eq "configured")
{
  system("$ENV{AUTOMINER_CCMINER_CRYPTONIGHT_PATH} -V 1>/dev/null 2>&1");
  print "yes\n" if $? == 0;
}
elsif($ARGV[0] eq "algos")
{
  print("cryptonight\n");
}
elsif($ARGV[0] eq "mine")
{
  my @cmd = (
      "$ENV{AUTOMINER_CCMINER_CRYPTONIGHT_PATH}"
    , "-o", "stratum+tcp://$ENV{AUTOMINER_ALGO}.usa.nicehash.com:$ENV{AUTOMINER_PORT}"
    , "-u", "$ENV{AUTOMINER_USERNAME}"
  );

  if(defined $ENV{AUTOMINER_CARDS_COMMAS})
  {
    push @cmd, "-d", "$ENV{AUTOMINER_CARDS_COMMAS}";
  }

  print STDERR (" >> ccminer-cryptonight : @cmd\n");

  POSIX::dup2(1, 2) or die;
  exec { $cmd[0] } @cmd;
}
elsif($ARGV[0] eq "perf")
{
  while(my $line = <STDIN>)
  {
    chomp $line;

    if($line =~ / ([0-9.]+) (k|m|g|t|p)?h\/s/i)
    {
      my $rate = $1;
      my $units = $2 || '';

      my $record = sprintf("%10u %s %sh/s\n", time() - $^T, $rate, $units);
      POSIX::write(1, $record, length($record));
    }
  }
}
